INSERT INTO ALIEN (AID, ANAME, TECH) VALUES (101, 'Verstappen', 'RedBull');
INSERT INTO ALIEN (AID, ANAME, TECH) VALUES (102, 'Lewis', 'Mercedes');
INSERT INTO ALIEN (AID, ANAME, TECH) VALUES (103, 'Perez', 'RedBull');
INSERT INTO ALIEN (AID, ANAME, TECH) VALUES (104, 'Sainz', 'Ferrari');
INSERT INTO ALIEN (AID, ANAME, TECH) VALUES (105, 'Ricciardo', 'McLaren');